Today is the 15 Day of our Machile Learning challenge where we will write a code in order to learn Machine Learning every single day.
From today we will learn and perform some numpy operations and to the Machine Learning models starting from Linear Regression.
Today we will see what is matrix and see some operations on it

In [2]:
#Let's import package needed for working with matrices 
import numpy as np

In [13]:
#Let's create 1-dimensional array
np.random.randint(100, size=(5))

array([ 6, 67, 17, 29, 39])

In [14]:
#Now Let's create 2-dimensional array
np.random.randint(100, size=(5,3))

array([[94, 87, 84],
       [97, 13, 60],
       [70, 58, 13],
       [11, 32,  0],
       [52, 45, 65]])

In [15]:
#In order to create matrix with float numbers you should use another method of numpy package
#This is 1 dimensional
np.random.rand(5)

array([0.41663255, 0.5219432 , 0.61919175, 0.14015469, 0.27903603])

In [16]:
#This is 2-dimensional
np.random.rand(5,3)

array([[0.11459615, 0.70400711, 0.88751906],
       [0.53869071, 0.55580591, 0.02747101],
       [0.52307857, 0.02450002, 0.99175533],
       [0.03476443, 0.80785648, 0.06787924],
       [0.58192767, 0.91870317, 0.53151721]])

In [18]:
#We can multpily matrices between each other
#For that np.dot method is required
a = np.random.randint(100, size=(2,3))
b = np.random.randint(100, size=(3,2))
#remember that number of columns of first matrix should be equal to rows of second matrix
c = np.dot(a,b)

In [20]:
a,b

(array([[95, 46, 24],
        [82, 50,  1]]),
 array([[97, 20],
        [39, 65],
        [52, 62]]))

In [21]:
c

array([[12257,  6378],
       [ 9956,  4952]])

In [ ]:
#We can also transpose our matrix 
#This can help to change the dimeonsionality of our matrix
c.T
#We can see that values has changed

array([[12257,  9956],
       [ 6378,  4952]])

In [38]:
#here we will find the inverse of the matrix
d = np.random.randint(100, size=(3,3))
np.linalg.inv(d)

array([[ 0.02690763, -0.00290575, -0.00553663],
       [ 0.00684226, -0.01569694,  0.01063151],
       [-0.00776012,  0.01780262,  0.00013743]])

So today in our challenge we have seen what are the matrices. 
We have seen how to perform some calculations. In further days we will learn how to deploy some models and train our own models.